### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#26]
A few maintenance issues exist, including : 

- [[Issue 4](https://github.com/neuropoly/slicer-manual-annotation/issues/4)] : for choosing and implementing code style conventions
- [[Issue 25](https://github.com/neuropoly/slicer-manual-annotation/issues/25)] : for adding unit tests 

**Current issue**

- refactor functions to be less bulky 
- remove duplicate code 
- split code into multiple files to improve readability

**Comment by maxradx** [comment]
Outdated. Many development since this issue. Code now clean. Will open new issues if specific code refractoring is needed. For example, [issue 40](https://github.com/neuropoly/slicer-manual-annotation/issues/40) addresses code fragmentation and is now addressed (discussions remain to be done about how to divide the code: will take place at the next meeting about the slicer module)
