### ISSUE TITLE
Substitute the need of config.yaml by a configuration GUI

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#3]
This 3D Slicer module enables to customize configuration settings from a configuration file config.yaml.
This might not be user-friendly for users with different background (e.g. clinicians, medical students without informatic knowledge/background).

Action tasks:

- [x] Stay up-to-date with @delphinepilon work in Dr. Létourneau-Guillon's repo in creating a GUI for initial app configuration
- [ ] Extend configurable options:
- [ ] Distinct configuration if working on MRI or Scans
- [ ] Distinct configuration according to the convention on how files are named (e.g. BIDS vs others)
- [ ] Enable easy add-ups

**Comment by delphinepilon** [comment]
**Update from branch SlicerCART to be incorporated into main**

Current configuration files : label_config.yml ; classification_config.yml ; general_config.yml ; keyboard_shortcuts_config.yml 

**Current behaviour**

The user must modify manually the configuration files to obtain the desired behaviour in the GUI interface. 

**Expected behaviour**

The user should be able to configure their GUI through a configuration window upon startup. All the options in the configuration files should be available. There should be an option to use the same configurations each time the user opens 3D Slicer. Also, it should be possible for the user to share their configurations to another user, say a member of their team, so that there can be multiple annotators with the same configuration for the same task. 

- specify which task is to be performed : segmentation, classification, or both
- specify which imaging modality : MRI or CT
- specify whether the BIDS format should be imposed (cannot be imposed in case of modality == CT, not supported)
- if task is segmentation, specify the labels (name, value, colour, if CT : hounsfield unit range)
- if task is classification, specify the checkboxes, comboboxes (dropdowns), and free text fields
- specify if the initial view should be axial, sagittal, or coronal (Red, Yellow, Green)
- specify the default value for interpolate (0 or 1)
- specify if it is an assessment mode (see #23)
- etc.

**Comment by maxradx** [comment]
Ok great! Thanks for sharing! In the task that could be performed, maybe add 'assessment'? (for example if the annotator wants to assess self consistency among its segmentations and\or would like to train from a specific bunch of cases?)

**Comment by delphinepilon** [comment]
Yes, indeed ! I've updated my previous comment in consequence.

**Comment by maxradx** [comment]
#5

**Comment by maxradx** [comment]
#5 is related to this discussion.
