### ISSUE TITLE
Splitting code in subfolder

### ISSUE THREAD

**Issue by laurentletg** [neuropoly/slicer-manual-annotation#40]
**Is your feature request related to a problem? Please describe.**
The main script is too long. 

**Describe the solution you'd like**
While the ideal solution would be to split the code in subfolders/modules, my attempts to make it work in Slicer always end up with `ModuleNotFoundError`. This is usually easy to perform in standard Python scripts but not through Slicer. There is a post about this [here](https://discourse.slicer.org/t/importing-custom-python-module-into-scripted-extension/11673) but I was not able to make it work even after updating the path like so:

```py
script_directory = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(script_directory, 'name_of_module'))
```

**Comment by maxradx** [comment]
I have asked the 3D Slcier forum. Here is one answer: https://discourse.slicer.org/t/slicer-development-code-fragmentation/38516/3 

- [ ] To test!

**Comment by maxradx** [comment]
Hi,

Issue 40 will be solved soon in @AcastaPaloma  pull requests. In addition, we found and tested how to use/split the code in different files in a subFolder.

Example of organization:

<img width="432" alt="image" src="https://github.com/user-attachments/assets/3f7bd788-133b-45f9-871d-598f63452b42">

On the same level than the file SlicerCART.py (main script file), an additional folder is created (ie, subfolder), which contains one or multiple python files that have content to be re-used in the main script (SlicerCART.py file).

In the main .py file (e.g. SlicerCART.py), you use the following syntax: `import subFolder.SlicerConfigurationWindows as aaa `where:
subfolder is the name of the subfolder 
‘SlicerConfigurationWindows’ is the name of the child python file
‘aaa’ is the abbreviation used in the main script to call the method

In a child python file (e.g. SlicerConfigurationWindow.py), you can insert your functions that you want to use in the main python script. You can also import the content of another child python file in the same subfolder by doing `import subFolder.CheckFunctions as cf `where:
subfolder is the folder location of this child python file
‘CheckFunctions’ is the name of the other python file to be re-used in this child python file
‘cf’ is the abbreviation used in this child python file to call the method


*Note that Slicer python interpreter will always consider the path from the main python file associated with the module. This means that if you want to import a child python file at the same level than another python file, you must specify the location according to the main python file. For example: to import subFolder.CheckFunctions.py in subFolder.SlicerConfigurationWindows.py, you must write `import subFolder.CheckFunctions as cf` in the code line of subFolder.SlicerConfigurationWindows (see image below).

<img width="432" alt="image" src="https://github.com/user-attachments/assets/ed9249ed-c01a-4ad2-b0c0-ef9fada1fc67">

In each child python file (e.g. CheckFunctions.py), it is recommended to add the following imports:
```
from slicer.ScriptedLoadableModule import *
from slicer.util import VTKObservationMixin
```

Thanks.

**Comment by laurentletg** [comment]
Thanks for your investigation. 

This seems to be the standard Python way of modularizing code. Is there any specific item besides adding the 2 lines you mentioned at the end of your post ?

Few questions:
- [ ] Should you add a `__init__.py` file in `subFolder` ? 
- [ ] What naming conventions should be used  for `subFolder` ? Per [PEP8](https://peps.python.org/pep-0008/#package-and-module-names) it think modules should be lowercase but I know that Slicer uses C++/CamelCase also.  
- [ ] In the past I was able to split some of the code (e.g. qt components) outside of the main module script but each change to these separate scripts required a 3D Slicer restart instead of using the reload button : this is annoying when developing a module because of the time it takes to restart Slicer.

**Comment by maxradx** [comment]
Question  related to the strategy approach for solving this issue (since preliminary testing worked).

@jcohenadad @laurentletg @AcastaPaloma 

Is it better to commit a branch with a basic organization that shows it's working (e.g. with a python file in a subfolder that helps debugging), or fragment the code (e.g. according to classes, etc.) and create a PR that will be discussed at the next meeting, for example? (for my part, I'd tend to discuss with the team how we should divide the code rather than jumping right in, and then make an 'EPIC' PR given the big changes such a PR will have)

What do you think?

Thanks.

**Comment by jcohenadad** [comment]
@mguaypaq @joshuacwnewton are more qualified to answer this question

**Comment by mguaypaq** [comment]
The problem with "epic" PRs is that they're hard to make, but even harder to review. It's typically much easier to make and review incremental changes (for example, splitting off one class at a time).

Also, to decide how code should be organized, I find that up-front discussion is not very useful, because it always overlooks some small but impactful technical details (for example, circular dependencies, or forgetting that one part of the code calls a different part). It's usually much more productive for 1 or 2 people to sit down and make a prototype/proof of concept of the reorganization, and write down which constraints or trade-offs they encounter. It's very likely that the first prototype gets thrown away, but it can still inform the second try. And it's a concrete thing that can guide the discussion (if there's a discussion).

**Comment by maxradx** [comment]
Hi @mguaypaq and team,

Thank you, a lot, for your insight, it is very appreciated!

Here is a scheme resuming the SlicerCart main python file for the module (image below).

Proposed approach for splitting the code in subfolder would consist of 2 main steps:

1. PR where modules to import, functions for checking and installing python packages and Global variables and function would be in other separate python files, from the actual main branch code.
          2. A file where all import modules required for running the module would be there (1 line of code repeated in each file?)
          3. Good idea to create a requirements.txt file?
2. PR would incrementally separate the different classes, as proposed, thereby reducing the length of the main SlicerCART.py file by executing classes from different files. 

ToDo:

- [ ] Discuss this approach at next Neuropoly Slicer meeting scheduled on Friday November 8th, 2024.

<img width="515" alt="image" src="https://github.com/user-attachments/assets/5238fef9-e257-4987-b14a-456684c885af">

**Comment by maxradx** [comment]
Note that the PR 98 is only intended to partially solve the issue 40. Will need other PR / resucommit to complete successfull code fragmentation.

**Comment by maxradx** [comment]
Mini-Update related to this issue. Working on a branch. Almost done, but facing circular import issues. Will try to fix and PR once fixed (hopefully soon)
